- hosts: all
  tasks:
    - name: Simulate a restart
      ansible.builtin.command: sleep 5
    
    - name: print success
      ansible.builtin.debug:
        msg: "Service is {{ state }}. Restarted successfully."
        